### ISSUE TITLE
No way to implement Remote Command: Firebase

### ISSUE THREAD

**Issue by fsanz92** [Tealium/tealium-android-firebase-remote-command#14]
Hi everyone! 🖖 

I am opening this Issue because I am following your guide to implement Tealium remote command integration for Firebase on Android through the dependency manager:

1. Install [Tealium for Android (Kotlin)](https://docs.tealium.com/platforms/android-kotlin/install/) or [Tealium for Android (Java)](https://docs.tealium.com/platforms/android-java/install/) and add the Tealium Maven URL to your project’s top-level build.gradle file, if you haven’t done so already.

```
allprojects {
  repositories {
    jcenter()
    maven {
      url "https://maven.tealiumiq.com/android/releases/"
    }
  }
}
```

2. Add the following dependency your build.gradle file:
```
dependencies {
    implementation 'com.tealium.remotecommands:firebase:1.2.0'
}
```
3. Initialize - Android (Kotlin)

```
val config = TealiumConfig(application,
        "ACCOUNT",
        "PROFILE",
        Environment.DEV,
        dispatchers = mutableSetOf(Dispatchers.RemoteCommands, Dispatchers.TagManagement));
        
val firebase = FirebaseRemoteCommand(application);
```

But there is no way to implement `FirebaseRemoteCommand(application)`, Android Studio returns an `Unresolved reference` error.

Am I missing anything? The documentation does not give any further information on this.

Thanks in advance!

**Comment by jameskeith** [comment]
@fsanz92 thanks for raising this with us.
The fully qualified class name will be `com.tealium.remotecommands.firebase.FirebaseRemoteCommand` - I'd expect Android Studio to offer you the option to import that though.

The Maven url specified looks okay to me too. I've had a quick look at my end and can see that `1.2.0` is published and available where I'd expect it to be, and that the relevant class is present in the binary.
The latest version is actually `1.3.0` - looks like our documentation is slightly outdated so we'll get that updated.

Do you happen to have a sample project where you can replicate the behaviour?

**Comment by jameskeith** [comment]
Thanks for the additional information.

All of our published maven artefacts live in the same Maven repository, so if the project can successfully import `com.tealium:kotlin-remotecommand-dispatcher` then there's no reason for that same project/module to be able to import `com.tealium.remotecommands:firebase` as a dependency also.
Depending on the age of the Android Studio project, where to add your `allProjects` repositories can differ as well though. The Legacy approach is to add it directly into the project level `build.gradle` similar to how our documentation shows it. Otherwise in newer projects it's expected to be placed in the `settings.gradle` file; something like the following:
```
//...
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        maven {
            url "https://maven.tealiumiq.com/android/releases/"
        }
    }
}
//...
```
All of the above assumes your build files are groovy based instead of using the Kotlin DSL in your project - the syntax will be broadly similar.


The remote command implementations (Firebase included) don't transitively import the rest of our Android Kotlin/Java SDK requirements because they are SDK-agnostic and supported on both. The documentation assumes that you already have one or the other already configured in your application. We recommend people to use our Kotlin SDK.
So for clarity, there should be the following dependencies as a minimum for the Firebase Remote Command in the module that you intend to use it in.
```
    implementation 'com.tealium:kotlin-core:1.5.3'
    implementation 'com.tealium:kotlin-remotecommand-dispatcher:1.3.0'
    implementation 'com.tealium.remotecommands:firebase:1.3.0'
```

I can confirm that I'm able to create a brand new Android application project and successfully import all of those dependencies without issue - and am able to compile/build without error.

**Comment by fsanz92** [comment]
Hello again @jameskeith ! I have tried to make a clean configuration of the library following your steps and checking everything in detail, and I have managed to get it to work. Therefore, we can consider the issue as solved and close it. Thanks for your help and sorry for the inconvenience.

**Comment by jameskeith** [comment]
thanks @fsanz92  - that's good to hear.
If you have any further issues then obviously feel free to let us know.
